<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\CodesysML\CodesysML\CodesysML.csproj" />
    <ProjectReference Include="..\..\PlcOpenML\PlcOpenML\PlcOpenML.csproj" />
    <ProjectReference Include="..\CipDeviceProfil\Odva.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Builders\" />
    <Folder Include="Factories\" />
  </ItemGroup>
</Project>
